# Generated by Django 4.0.4 on 2022-05-22 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_downvotemodel_tipmodels_upvotemodel_tipmodels_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='downvotemodel',
            name='tipmodels',
        ),
        migrations.RemoveField(
            model_name='upvotemodel',
            name='tipmodels',
        ),
    ]
